export const listDevice = [
  {
    name: 'Máy trợ tim',
    madeYear:'2009',
    code:'TT-29',
    madeIn:'Korea',
    useIn: 'VN',
    dateReceived:'20/7/2016',
    dateUse:'20/9/2016',
    price:'$2000',
    description:'Máy hỗ trợ nhịp tim',
    voltageFrom:'200',
    voltageTo:'400',
    ampe:'100',
    capacity:'',
    accessory:'',
    receiver:'QuyenDT',
    moneySource:'Trên cấp',
    dateIn:'15/07/2016',
    statusReceipt:'Mới hoàn toàn',
    levelQuality:'II',
  },
  {
    name: 'Máy Chụp X-Quang',
    madeYear:'2009',
    code:'TT-29',
    madeIn:'Korea',
    useIn: 'VN',
    dateReceived:'20/7/2016',
    dateUse:'20/9/2016',
    price:'$2000',
    description:'Chụp X-Quang băng tia hồng ngoại nhập khẩu từ Hàn Quốc',
    voltageFrom:'200',
    voltageTo:'400',
    ampe:'100',
    capacity:'',
    accessory:'',
    receiver:'QuyenDT',
    moneySource:'Trên cấp',
    dateIn:'15/07/2016',
    statusReceipt:'Mới hoàn toàn',
    levelQuality:'II',
  },
  {
    name: 'Kim tiêm HNH2',
    madeYear:'2009',
    code:'TT-29',
    madeIn:'USA',
    useIn: 'VN',
    dateReceived:'20/7/2016',
    dateUse:'20/9/2016',
    price:'$2000',
    description:'Kim tiêm HNH2 loại mới nhập khẩu từ Mỹ',
    voltageFrom:'200',
    voltageTo:'400',
    ampe:'100',
    capacity:'',
    accessory:'',
    receiver:'QuyenDT',
    moneySource:'Trên cấp',
    dateIn:'15/07/2016',
    statusReceipt:'Mới hoàn toàn',
    levelQuality:'II',
  },
  {
    name: 'Dao mổ',
    madeYear:'2010',
    code:'TT-29',
    madeIn:'China',
    useIn: 'VN',
    dateReceived:'20/7/2016',
    dateUse:'20/9/2016',
    price:'$2000',
    description:'Dao mổ nhập khẩu từ Trung Quốc',
    voltageFrom:'200',
    voltageTo:'400',
    ampe:'100',
    capacity:'',
    accessory:'',
    receiver:'QuyenDT',
    moneySource:'Trên cấp',
    dateIn:'15/07/2016',
    statusReceipt:'Mới hoàn toàn',
    levelQuality:'II',
  },
                
  ]
  